site_title: cloudness
publisher_name: Alex Neagu
profile_role: Cloud Engineering Director
home_intro_primary: "I\u2019m an engineer turned manager with over 100 cloud projects\
  \ delivered. From infrastructure to AI, hands-on work with technology remains the\
  \ best part of my day. With a background in architecture and a customer-facing role,\
  \ I help organizations across sizes and industries maximize the value of their cloud\
  \ investments."
home_intro_secondary: "Confident across the stack, I\u2019ve delivered solutions on\
  \ all major hyperscalers. My focus is on scaling distributed systems, enabling DevOps\
  \ culture, and democratizing artificial intelligence.\r\n\r\nHappy to share. What\
  \ works. What doesn\u2019t. No fluff."
