site_title: cloudness
publisher_name: Alex Neagu
profile_role: ''
linkedin_url: https://www.linkedin.com/in/neagualex/
social_image_url: ''
home_intro_primary: "I\u2019m an engineer turned manager with over 100 cloud projects\
  \ delivered. I help organizations across sizes and industries maximize the value\
  \ of their cloud investments. My focus is on scaling distributed systems, enabling\
  \ DevOps culture, and democratizing artificial intelligence. Happy to share what\
  \ works and what doesn't."
